language: bash

before_script:
    - sh extras/travis-ci/before_script.sh

script:
    - cd .. && cd ./felcon-sdk && sh felcon-devkit run unit-tests

notifications:
  email:
    recipients:
      - felcon-dev@felcon.com
    on_success: change
    on_failure: always
